spring.application.name=Semantics

rdf.storage.directory=./data
rdf.storage.filename.base=baseData.ttl
rdf.storage.filename.snapshot=snapshot.ttl
rdf.storage.filename.update=journal.log

domain.storage.directory=./data/domain
domain.storage.filename.history=history.log